import * as MaterialCore from '@mui/material';
import * as MaterialStyles from '@mui/material/styles';
import * as MaterialIcons from '@mui/icons-material';
import * as MaterialLab from '@mui/lab';

// Re-export everything from Material-UI Core
export const {
  Alert,
  AppBar,
  Avatar,
  Badge,
  Box,
  Button,
  Card,
  CardContent,
  CardHeader,
  Chip,
  CircularProgress,
  Container,
  CssBaseline,
  Dialog,
  DialogActions,
  DialogContent,
  DialogContentText,
  DialogTitle,
  Divider,
  Drawer,
  FormControl,
  FormControlLabel,
  GlobalStyles,
  Grid,
  IconButton,
  InputBase,
  InputLabel,
  LinearProgress,
  List,
  ListItem,
  ListItemButton,
  ListItemIcon,
  ListItemText,
  Menu,
  MenuItem,
  Paper,
  Radio,
  RadioGroup,
  Select,
  Snackbar,
  Step,
  StepLabel,
  Stepper,
  Tab,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TablePagination,
  TableRow,
  Tabs,
  TextField,
  Toolbar,
  Tooltip,
  Typography,
  useTheme,
} = MaterialCore;

// Re-export styles
export const { alpha, createTheme, ThemeProvider } = MaterialStyles;

// Re-export icons
export const {
  AccountCircle,
  Add: AddIcon,
  Analytics: AnalyticsIcon,
  Brightness4: DarkModeIcon,
  CheckCircle: CheckCircleIcon,
  ChevronLeft: ChevronLeftIcon,
  ChevronRight: ChevronRightIcon,
  CloudUpload: CloudUploadIcon,
  ContentCopy: ContentCopyIcon,
  Dashboard: DashboardIcon,
  Delete: DeleteIcon,
  Edit: EditIcon,
  Email: EmailIcon,
  ExpandLess,
  ExpandMore,
  Help: HelpIcon,
  Language: LanguageIcon,
  Link: LinkIcon,
  Logout: LogoutIcon,
  Menu: MenuIcon,
  Message: MessageIcon,
  Notifications: NotificationsIcon,
  NotificationsActive: NotificationsActiveIcon,
  Person: PersonIcon,
  Phone: PhoneIcon,
  Recommend: RecommendIcon,
  Schedule: ScheduleIcon,
  Search: SearchIcon,
  Security: SecurityIcon,
  Send: SendIcon,
  Settings: SettingsIcon,
  Storage: StorageIcon,
  Warning: WarningIcon,
} = MaterialIcons;

// Re-export lab components
export const { LoadingButton } = MaterialLab; 