// Material-UI Core exports
export {
  Alert,
  AppBar,
  Avatar,
  Badge,
  Box,
  Button,
  Card,
  CardContent,
  CardHeader,
  Chip,
  CircularProgress,
  Container,
  CssBaseline,
  Dialog,
  DialogActions,
  DialogContent,
  DialogContentText,
  DialogTitle,
  Divider,
  Drawer,
  FormControl,
  FormControlLabel,
  GlobalStyles,
  Grid,
  IconButton,
  InputBase,
  InputLabel,
  List,
  ListItem,
  ListItemButton,
  ListItemIcon,
  ListItemText,
  Menu,
  MenuItem,
  Paper,
  Radio,
  RadioGroup,
  Select,
  Snackbar,
  Step,
  StepLabel,
  Stepper,
  Tab,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TablePagination,
  TableRow,
  Tabs,
  TextField,
  Toolbar,
  Tooltip,
  Typography,
  useTheme,
} from '@mui/material';

// Material-UI Styles exports
export { alpha, createTheme, ThemeProvider } from '@mui/material/styles';

// Material-UI System exports
export type { SxProps } from '@mui/system';

// Material-UI Icons exports
export {
  AccountCircle,
  Add as AddIcon,
  Analytics as AnalyticsIcon,
  Brightness4 as DarkModeIcon,
  CheckCircle as CheckCircleIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  CloudUpload as CloudUploadIcon,
  ContentCopy as ContentCopyIcon,
  Dashboard as DashboardIcon,
  Delete as DeleteIcon,
  Edit as EditIcon,
  Email as EmailIcon,
  ExpandLess,
  ExpandMore,
  Help as HelpIcon,
  Language as LanguageIcon,
  Link as LinkIcon,
  Logout as LogoutIcon,
  Menu as MenuIcon,
  Message as MessageIcon,
  Notifications as NotificationsIcon,
  NotificationsActive as NotificationsActiveIcon,
  Person as PersonIcon,
  Phone as PhoneIcon,
  Recommend as RecommendIcon,
  Schedule as ScheduleIcon,
  Search as SearchIcon,
  Security as SecurityIcon,
  Send as SendIcon,
  Settings as SettingsIcon,
  Storage as StorageIcon,
  Warning as WarningIcon,
} from '@mui/icons-material';

// Material-UI Lab exports
export { LoadingButton } from '@mui/lab'; 