# Generated by Django 5.2.1 on 2025-06-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedmessage',
            name='custom_text',
            field=models.TextField(blank=True),
        ),
    ]
