# Generated by Django 5.2.1 on 2025-06-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_add_custom_text_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='client',
            name='Contract',
            field=models.CharField(choices=[('Month-to-month', 'Month-to-month'), ('One year', 'One year'), ('Two year', 'Two year')], default='Month-to-month', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='Dependents',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='client',
            name='DeviceProtection',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ('No internet service', 'No internet service')], default='No', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='InternetService',
            field=models.CharField(choices=[('DSL', 'DSL'), ('Fiber optic', 'Fiber optic'), ('No', 'No')], default='No', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='MonthlyCharges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='client',
            name='MultipleLines',
            field=models.CharField(choices=[('No phone service', 'No phone service'), ('No', 'No'), ('Yes', 'Yes')], default='No phone service', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='OnlineBackup',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ('No internet service', 'No internet service')], default='No', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='OnlineSecurity',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ('No internet service', 'No internet service')], default='No', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='PaperlessBilling',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='client',
            name='Partner',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='client',
            name='PaymentMethod',
            field=models.CharField(choices=[('Electronic check', 'Electronic check'), ('Mailed check', 'Mailed check'), ('Bank transfer (automatic)', 'Bank transfer (automatic)'), ('Credit card (automatic)', 'Credit card (automatic)')], default='Electronic check', max_length=30),
        ),
        migrations.AddField(
            model_name='client',
            name='PhoneService',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='client',
            name='SeniorCitizen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='StreamingMovies',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ('No internet service', 'No internet service')], default='No', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='StreamingTV',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ('No internet service', 'No internet service')], default='No', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='TechSupport',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ('No internet service', 'No internet service')], default='No', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='TotalCharges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='tenure',
            field=models.IntegerField(default=0),
        ),
    ]
