# Generated by Django 5.2.1 on 2025-06-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_alter_client_options_client_contract_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentimentanalysis',
            name='confidence',
        ),
        migrations.AddField(
            model_name='sentimentanalysis',
            name='probabilities',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='sentimentanalysis',
            name='sentiment',
            field=models.CharField(choices=[('très négatif', 'Très négatif'), ('négatif', 'Négatif'), ('neutre', 'Neutre'), ('positif', 'Positif'), ('très positif', 'Très positif'), ('inconnu', 'Inconnu')], max_length=20),
        ),
    ]
