# Generated by Django 5.2.1 on 2025-06-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_remove_sentimentanalysis_confidence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedmessage',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='generatedmessage',
            name='custom_text',
        ),
        migrations.RemoveField(
            model_name='generatedmessage',
            name='recommended_offer',
        ),
        migrations.RemoveField(
            model_name='generatedmessage',
            name='tone',
        ),
        migrations.AddField(
            model_name='generatedmessage',
            name='max_tokens',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='generatedmessage',
            name='model_response',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='generatedmessage',
            name='prompt',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='generatedmessage',
            name='temperature',
            field=models.FloatField(default=0.7),
        ),
    ]
