# Generated by Django 5.2.1 on 2025-06-11 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0005_update_generated_message_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedmessage',
            name='channel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='generatedmessage',
            name='recommended_offer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedmessage',
            name='tone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='generatedmessage',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predictor.client'),
        ),
        migrations.AlterField(
            model_name='generatedmessage',
            name='max_tokens',
            field=models.IntegerField(default=200, null=True),
        ),
        migrations.AlterField(
            model_name='generatedmessage',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generatedmessage',
            name='temperature',
            field=models.FloatField(default=0.7, null=True),
        ),
    ]
